abbr --add --global pen 'cd ~/boldpenguin'
abbr --add --global bold 'pen'
abbr --add --global cdbp 'pen'
abbr --add --global ce 'cd ~/boldpenguin/carrier-engine'
abbr --add --global re 'cd ~/boldpenguin/rules-engine'
abbr --add --global pe 'cd ~/boldpenguin/partner-engine'
abbr --add --global pp 'cd ~/boldpenguin/partner-portal'
abbr --add --global ba 'cd ~/boldpenguin/bold-appetit'
abbr --add --global pport 'cd ~/boldpenguin/progressive-portal'
abbr --add --global emperor 'cd ~/boldpenguin/emperor'
abbr --add --global pgate 'cd ~/boldpenguin/progressive-gateway'
abbr --add --global pqi 'cd ~/boldpenguin/pqi'
abbr --add --global auth 'cd ~/boldpenguin/authenticator'
abbr --add --global naics 'cd ~/boldpenguin/naics-engine'
abbr --add --global bp-auth 'cd ~/boldpenguin/bp-auth'
abbr --add --global ode 'cd ~/boldpenguin/aws-canary'
abbr --add --global t2 'cd ~/boldpenguin/terminal'
abbr --add --global pool 'cd ~/boldpenguin/carpool'
abbr --add --global carpool 'pool'
abbr --add --global ete 'cd ~/boldpenguin/bp-end-to-end'
abbr --add --global interview 'cd ~/boldpenguin/interview'
abbr --add --global eit 'cd ~/boldpenguin/emperor-integration-test'
#abbr --add --global flushred 'redis-cli flushall'
#abbr --add --global redflush 'redis-cli flushall'
abbr --add --global mid_reset 'rails midvale:nuke && rails midvale:build_all && rails patches:20200515135342_setup_midvale_for_test'
abbr --add --global ru 'cd ~/boldpenguin/pengie-raft && BP_ELASTICSEARCH_PORT=9200 BP_REDIS_PORT=6379 docker-compose up -d elasticsearch redis && cd -'
abbr --add --global flushredis 'docker exec -it raft_redis redis-cli FLUSHALL'
abbr --add --global flushred 'flushredis'
abbr --add --global redflush 'flushredis'
abbr --add --global pryable 'bundle exec puma -w 1 -p 8080'
abbr --add --global apryable 'bundle exec puma -w 1 -p 3000'
abbr --add --global pgup 'rails db:drop && rails db:create && psql partner_engine_development '
abbr --add --global amfamseed 'bin/rails amfam_dev:seed'
abbr --add --global pehelp 'more ~/.pryrc'

abbr --add --global pg_start "launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"
abbr --add --global pg_stop "launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"
